kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kratos-demo
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
  - containerPort: 30090
    hostPort: 9090
    protocol: TCP
  - containerPort: 30686
    hostPort: 16686
    protocol: TCP
  - containerPort: 30000
    hostPort: 3000
    protocol: TCP
- role: worker
- role: worker