server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/kratos_demo?parseTime=True&loc=Local&charset=utf8mb4
  redis:
    network: tcp
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  mongodb:
    uri: mongodb://127.0.0.1:27017
    database: kratos_demo
    timeout: 10s
  rocketmq:
    name_servers:
      - 127.0.0.1:9876
    group_name: kratos_demo_group
    access_key: ""
    secret_key: ""
    namespace: ""
telemetry:
  tracing:
    endpoint: http://localhost:14268/api/traces
    sampler: 1.0
    batcher: 512
  metrics:
    addr: 0.0.0.0:9090
    path: /metrics
cron:
  enabled: true
  timezone: Asia/Shanghai
sms:
  providers:
    aliyun:
      enabled: true
      timeout: 30s
      retry_times: 3
      max_batch_size: 1000
      config:
        access_key_id: "your_aliyun_access_key_id"
        access_key_secret: "your_aliyun_access_key_secret"
        sign_name: "your_sign_name"
        endpoint: "https://dysmsapi.aliyuncs.com"
    we:
      enabled: true
      timeout: 30s
      retry_times: 3
      max_batch_size: 500
      config:
        api_url: "https://api.we.com"
        api_key: "your_we_api_key"
        api_secret: "your_we_api_secret"
    xsxx:
      enabled: true
      timeout: 30s
      retry_times: 3
      max_batch_size: 200
      config:
        api_url: "https://api.xsxx.com"
        app_id: "your_xsxx_app_id"
        app_secret: "your_xsxx_app_secret"
  default_provider: "aliyun"
  load_balance_strategy: "round_robin"  # round_robin, random, weighted
  health_check_interval: 60s
